on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.64.0
        with:
          target: thumbv6m-none-eabi
          components: clippy
      - run: cargo clippy -- -A clippy::derive_partial_eq_without_eq -A clippy::explicit_auto_deref -D warnings
