on: [push, pull_request]
name: Code formatting check
jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
          components: rustfmt
      - run: cargo fmt --check
